version: "3.9"

services:
  db:
    image: postgres
    networks:
      sledre_lan:
        ipv4_address: 172.20.0.13
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    networks:
      sledre_lan:
        ipv4_address: 172.20.0.14

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: []
    command: celery -A api worker -l info
    networks:
      sledre_lan:
        ipv4_address: 172.20.0.15
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/backend:/data
    depends_on:
      - db
      - redis
      - api
    env_file:
      - ./.env

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: []
    command: celery -A api beat -l info
    networks:
      sledre_lan:
        ipv4_address: 172.20.0.16
    volumes:
      - ./backend:/app
    depends_on:
      - celery
    env_file:
      - ./.env

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      sledre_lan:
        ipv4_address: 172.20.0.12
    volumes:
      - ./backend:/app
      - ./data/backend:/data
    depends_on:
      - db
    env_file:
      - ./.env

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    networks:
      sledre_lan:
        ipv4_address: 172.20.0.11
    volumes:
      - ./frontend:/usr/src/app/
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - api
    environment:
      - NODE_ENV=development

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      sledre_lan:
        ipv4_address: 172.20.0.10
    environment:
      - NGINX_PORT=80
    depends_on:
      - front
      - api

volumes:
  node_modules:

networks:
  sledre_lan:
    driver: bridge
    internal: ${ISOLATED_NETWORK}
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
