name: BackendCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Run for each python version
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - name : Checkout - AutoDetours repository
        uses: actions/checkout@v2
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
  
  codingstyle:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "./backend --check"

